# Generated by Django 5.1.6 on 2025-04-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipe_author_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
